FROM python:3.9-slim-buster

# Comando que vai fazer aparecer as mensagens de logs
ENV PYTHONUNBUFFERED True
ENV APP_HOME /app
ENV HOST_API_CHAT app_chat
ENV HOST_API_DOC app_doc

## copiando todos os arquivos do diretório para o workdir no container
WORKDIR $APP_HOME
COPY . .

## rodando os comandos de pip para instalar as dependências
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

## comando que irá dar o start no container
CMD streamlit run app_interface.py --server.port=$PORT_INTERFACE